fragment ShareTypeParts on ShareType {
  id
  name
  dividendRate
  withdrawalLimitCount
  withdrawalLimitPeriod
  withdrawalLimitLastReset
  withdrawalLimitShouldFee
  withdrawalLimitFee
  shareTypeInstances {
    instanceId
  }
}
