#import "@/graphql/fragments/pageInfo.gql"
#import "@/graphql/fragments/shareType.gql"

query availableShareTypes($first: PaginationAmount) {
  availableShareTypes(first: $first) {
    pageInfo {
      ...PageInfoParts
    }
    totalCount
    nodes {
      ...ShareTypeParts
    }
  }
}
