#import "../fragments/pageInfo.gql"
#import "../fragments/studentStockHistory.gql"

query studentStockHistory(
  $studentStockId: Long!,
  $first: Int = 25,
  $after: String,
  $order: StudentSortInput! = { datePosted: DESC }
) {
  studentStockHistory(
    instances: $instances,
    first: $first,
    after: $after,
    order: [$order]
  ) {
    pageInfo {
      ...PageInfoParts
    }
    totalCount
    nodes {
      ...StudentStockHistoryParts
    }
  }
}
