export const userRefreshToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOjEsInVuaXF1ZV9uYW1lIjoidGVzdEBkb21haW4udGxkIiwiZW1haWwiOiJ0ZXN0QGRvbWFpbi50bGQiLCJyb2xlIjoic3VwZXJ1c2VyIiwidXR5cCI6InVzZXIiLCJwcmUiOiJOIiwiZXhwIjo0MTAyNDcwMDAwLCJuYmYiOjE1MTYyMzkwMjIsImlhdCI6MTUxNjIzOTAyMn0.kJ5cj55o3lGUUdd9EuleLzSlnrAtm7eWcrBPZv3jdLA';

export const userPreregistrationToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOjEsInVuaXF1ZV9uYW1lIjoidGVzdEBkb21haW4udGxkIiwiZW1haWwiOiJ0ZXN0QGRvbWFpbi50bGQiLCJyb2xlIjoic3VwZXJ1c2VyIiwidXR5cCI6InVzZXIiLCJwcmUiOiJZIiwiZXhwIjo0MTAyNDcwMDAwLCJuYmYiOjE1MTYyMzkwMjIsImlhdCI6MTUxNjIzOTAyMn0.9bGhHvuzR8cP3KbnRK186Usee1nnAjypbREaB_Yfuew';

export const expiredUserRefreshToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOjEsInVuaXF1ZV9uYW1lIjoidGVzdEBkb21haW4udGxkIiwiZW1haWwiOiJ0ZXN0QGRvbWFpbi50bGQiLCJyb2xlIjoic3VwZXJ1c2VyIiwidXR5cCI6InVzZXIiLCJwcmUiOiJOIiwiZXhwIjoxNTE2MjM5MDIyLCJuYmYiOjE1MTYyMzkwMjIsImlhdCI6MTUxNjIzOTAyMn0.I6bbv-va_BSDcl3iodajh39iHVuXLZqCQvurWvZSoNk';

export const studentRefreshToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOjEsInVuaXF1ZV9uYW1lIjoidGVzdEBkb21haW4udGxkIiwiZW1haWwiOiJ0ZXN0QGRvbWFpbi50bGQiLCJyb2xlIjoic3VwZXJ1c2VyIiwidXR5cCI6InN0dWRlbnQiLCJwcmUiOiJOIiwiZXhwIjo0MTAyNDcwMDAwLCJuYmYiOjE1MTYyMzkwMjIsImlhdCI6MTUxNjIzOTAyMn0.r_Y-2qpSlQYI_IS_UQyPfcAlPsgA9MrZEF9XVBcJHz0';

export const studentPreregistrationToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOjEsInVuaXF1ZV9uYW1lIjoidGVzdEBkb21haW4udGxkIiwiZW1haWwiOiJ0ZXN0QGRvbWFpbi50bGQiLCJyb2xlIjoic3VwZXJ1c2VyIiwidXR5cCI6InN0dWRlbnQiLCJwcmUiOiJZIiwiZXhwIjo0MTAyNDcwMDAwLCJuYmYiOjE1MTYyMzkwMjIsImlhdCI6MTUxNjIzOTAyMn0.zAxWdMNjitN0isVCZzcPZd1K9l_rJ-VyB_LeZZgx3Wk';

export const expiredStudentRefreshToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOjEsInVuaXF1ZV9uYW1lIjoidGVzdEBkb21haW4udGxkIiwiZW1haWwiOiJ0ZXN0QGRvbWFpbi50bGQiLCJyb2xlIjoic3VwZXJ1c2VyIiwidXR5cCI6InN0dWRlbnQiLCJwcmUiOiJOIiwiZXhwIjoxNTE2MjM5MDIyLCJuYmYiOjE1MTYyMzkwMjIsImlhdCI6MTUxNjIzOTAyMn0.zu1xl1aH_9HAA8U6DycX-AiKNoJC-vxfDsCsEPE6uJk';
