#import "../fragments/group.gql"

query groupsByInstance($instanceId: Long) {
  groups(
    where: {
      instanceId: { eq: $instanceId },
    },
    order: { name: ASC }
  ) {
    nodes {
      ...GroupParts
    }
  }
}
