#import "../fragments/pageInfo.gql"
#import "../fragments/student.gql"

query studentsWithShares(
  $first: Int,
  $after: String,
  $order: StudentSortInput! = {lastName: ASC},
  $groupId: Long,
) {
  students(
    first: $first,
    after: $after,
    order: [$order]
    where: {
      groupId: { eq: $groupId }
    },
  ) {
    pageInfo {
      ...PageInfoParts
    }
    totalCount
    nodes {
      ...StudentParts
    }
  }
}
