#import "../fragments/pageInfo.gql"
#import "../fragments/student.gql"

query studentsByName(
  $first: Int = 25,
  $order: StudentSortInput! = { accountNumber: ASC },
  $name: String!
) {
  students(
    first: $first,
    order: [$order],
    where: {
      or: [
        {
          firstName: { startsWithInvariant: $name}
        },
        {
          lastName: { startsWithInvariant: $name}
        }
      ]
    },
  ) {
    pageInfo {
      ...PageInfoParts
    }
    totalCount
    nodes {
      ...StudentParts
    }
  }
}
