#import "@/graphql/fragments/pageInfo.gql"
#import "@/graphql/fragments/transaction.gql"

query transactions(
  $shareId: Long!,
  $first: Int = 25,
  $after: String,
  $order: TransactionSortInput! = { effectiveDate: DESC }
) {
  transactions(
    shareId: $shareId,
    first: $first,
    order: [$order],
    after: $after
  ) {
    pageInfo {
      ...PageInfoParts
    }
    totalCount
    nodes {
      ...TransactionParts
    }
  }
}
