#import "../fragments/pageInfo.gql"
#import "../fragments/stock.gql"

query stocks(
  $first: PaginationAmount! = 25,
  $after: String,
) {
  stocks(
    first: $first,
    after: $after,
    order_by: { name: ASC }
  ) {
    pageInfo {
      ...PageInfoParts
    }
    totalCount
    nodes {
      ...StockParts
    }
  }
}
