#import "../fragments/pageInfo.gql"
#import "../fragments/stock.gql"

query stocks(
  $instances: [Long!],
  $first: PaginationAmount! = 25,
  $after: String,
  $where: StockFilter,
  $order_by: StockSort! = { name: ASC },
) {
  stocks(
    instances: $instances,
    first: $first,
    after: $after,
    where: $where,
    order_by: $order_by
  ) {
    pageInfo {
      ...PageInfoParts
    }
    totalCount
    nodes {
      ...StockParts
    }
  }
}
