#import "../fragments/pageInfo.gql"
#import "../fragments/stockHistory.gql"

query stockHistory(
  $stockId: Long!,
  $first: PaginationAmount! = 25,
  $after: String,
) {
  stockHistory(
    stockId: $stockId,
    first: $first,
    after: $after,
    order_by: { dateChanged: DESC }
  ) {
    pageInfo {
      ...PageInfoParts
    }
    totalCount
    nodes {
      ...StockHistoryParts
    }
  }
}
