query availableShareTypes {
  availableShareTypes {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    totalCount
    nodes {
      id
      name
      dividendRate
      shareTypeInstances {
        instanceId
      }
    }
  }
}