mutation newBulkTransaction($shares: [NewTransactionRequestInput!]!, $skipNegative: Boolean!) {
  newBulkTransaction(
    input: $shares,
    skipBelowNegative: $skipNegative
  ) {
    id
    targetShareId
    transactionType
    effectiveDate
    comment
    amount
    newBalance
  }
}
