mutation newStudent(
  $accountNumber: String!,
  $groupId: Long!,
  $firstName: String!,
  $lastName: String!,
  $password: String!,
  $email: String
) {
  newStudent(input: {
    accountNumber: $accountNumber,
    groupId: $groupId,
    firstName: $firstName,
    lastName: $lastName,
    password: $password,
    email: $email
  }) {
    id
    groupId
    accountNumber
    firstName
    lastName
    email
    group {
      id
      name
      instanceId
      instance {
        id
        description
      }
    }
    shares {
      id
      balance
      shareTypeId
      shareType {
        name
        dividendRate
      }
    }
  }
}
