query ShareTypes($instanceId: Long!, $first: PaginationAmount) {
  shareTypes(instanceId: $instanceId, first: $first) {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    totalCount
    nodes {
      id
      name
      dividendRate
      shareTypeInstances {
        instanceId
      }
    }
  }
}
