query studentsById($id: Long!) {
  students(
    where: { id: $id },
  ) {
    nodes {
      id
      groupId
      accountNumber
      firstName
      lastName
      email
      group {
        id
        name
        instanceId
        instance {
          id
          description
        }
      }
      shares {
        id
        balance
        shareType {
          name
          dividendRate
        }
      }
    }
  }
}
