query studentsWithShares($groupId: Long, $first: PaginationAmount, $after: String) {
  students(where: {groupId: $groupId}, first: $first, after: $after, order_by: {accountNumber: ASC}) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      endCursor
    }
    totalCount
    nodes {
      id
      groupId
      accountNumber
      firstName
      lastName
      email
      shares {
        balance
        shareType {
          name
          dividendRate
        }
      }
    }
  }
}
