query transactions(
  $shareId: Long!,
  $first: PaginationAmount! = 25,
  $after: String,
) {
  transactions(
    shareId: $shareId,
    first: $first,
    order_by: { effectiveDate: DESC },
    after: $after
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
    nodes {
      id
      transactionType
      effectiveDate
      comment
      amount
      newBalance
    }
  }
}
